### ISSUE TITLE
Widget Description Copy 

### ISSUE THREAD

**Issue by r-diamond** [copyblogger/Genesis-Author-Pro#19]
Currently, the widget description text reads

> Displays featured page with thumbnails

![image](https://cloud.githubusercontent.com/assets/3864662/15324374/8e228c7a-1c1c-11e6-96e1-93b488a84a4b.png)

This should be changed to more accurately reflect that it is a book widget.

Handing to @jerodm40 for first pass through copy please :) 

![image](https://cloud.githubusercontent.com/assets/3864662/15324246/0d55b2f2-1c1c-11e6-95cf-7899b95bb6d1.png)

![image](https://cloud.githubusercontent.com/assets/3864662/15324252/1311dde2-1c1c-11e6-96a3-d5cc779d7416.png)

![image](https://cloud.githubusercontent.com/assets/3864662/15324339/6df76d8a-1c1c-11e6-9996-01201b2701cd.png)

Related to https://github.com/copyblogger/synthesis-platform/issues/3125

**Comment by jerodm40** [comment]
Displays a single book with several customizable display options.

**Comment by r-diamond** [comment]
Sounds good to me - you guys too? cc: @omiq @katyfb13 @dreamwhisper

**Comment by omiq** [comment]
Yes

**Comment by dreamwhisper** [comment]
:+1:

**Comment by r-diamond** [comment]
Over to @claregarrett for final proofing :)

> Displays a single book with several customizable display options.

**Comment by claregarrett** [comment]
Looks good :)

**Comment by dreamwhisper** [comment]
@NicktheGeek I assigned you, but maybe Emma?

**Comment by Emdaisy1** [comment]
**Test Branch**: develop_1551_nc (needs to be on that branch to have the author pro book features enabled)

**Test Scenario**: Navigate to Design > Content Areas. View the Featured Book widget (note: due to an update made for issue 3126 in the synthesis-platform repo this widget is now titled "Author Pro - Featured Book" instead of "Genesis Author Pro - Featured Book".

**Test Verification**: 
- [x] The widget description reads "Displays a single book with several customizable display options." NOT "Displays featured page with thumbnails"

**Other Features/Areas Affected**: N/A

![authorprobookwidget](https://cloud.githubusercontent.com/assets/9681894/15368783/9a75b0c4-1cfd-11e6-95c4-2b1746671ea4.JPG)

**Comment by r-diamond** [comment]
Merge ready! :)

**Comment by r-diamond** [comment]
Package ready!
